### ISSUE TITLE
Head is not even barely the majority of this check-in...

### ISSUE THREAD

**Issue by AdamYuret** [chrismetcalf/my-head#1]
Sorry but there is a neck, shoulders and most of a chest on this check-in. Either expand the check in to include the rest of the torso and call it "my-torso" or delete the superfluous components leaving only the head proper.

**Comment by chrismetcalf** [comment]
Sorry, but I like my head attached to my neck, so I'm going to close this as `wontfix`

**Comment by AdamYuret** [comment]
![image](https://cloud.githubusercontent.com/assets/453734/6718030/e89ea430-cd6d-11e4-8ce9-604bc2d86cd5.png)
